# Generated by Django 5.0.6 on 2024-07-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
