# Generated by Django 5.0.6 on 2024-07-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
