# Generated by Django 5.0.6 on 2024-07-30 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('Annon_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annon_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
