# Generated by Django 5.0.6 on 2024-07-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Annon_username', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='amessages',
            name='Annon_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agl.annon'),
        ),
    ]
