# Generated by Django 5.0.6 on 2024-07-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agl', '0002_annon_alter_amessages_annon_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amessages',
            old_name='Annon_user',
            new_name='annon_user',
        ),
    ]
