# Generated by Django 5.0.6 on 2024-07-30 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agl', '0003_rename_annon_user_amessages_annon_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agl.amessages')),
            ],
        ),
    ]
