# Generated by Django 5.0.6 on 2024-07-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agl', '0005_anonchat_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonchat',
            name='group',
        ),
        migrations.AddField(
            model_name='annon',
            name='group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annon',
            name='pass_code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
