# Generated by Django 5.0.6 on 2024-07-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agl', '0006_remove_anonchat_group_annon_group_annon_pass_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonchat',
            name='message',
        ),
        migrations.AddField(
            model_name='anonchat',
            name='message',
            field=models.ManyToManyField(blank=True, related_name='anon_mess', to='agl.amessages'),
        ),
    ]
