# Generated by Django 5.0.6 on 2024-07-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agl', '0008_rename_annon_username_annon_annon_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annon',
            name='pass_code_user',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
