# Generated by Django 5.0.6 on 2024-07-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agl', '0009_annon_pass_code_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annon',
            name='pass_code_user',
        ),
    ]
