# Generated by Django 5.0.6 on 2024-07-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agl', '0013_alter_annon_annon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonchat',
            name='pass_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
