# Generated by Django 5.0.6 on 2024-07-30 22:48

import agl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agl', '0014_alter_anonchat_pass_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonchat',
            name='chat',
            field=models.CharField(default=agl.models.generate_short_uuid, editable=False, max_length=10, unique=True),
        ),
    ]
