# Generated by Django 5.0.6 on 2024-07-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agl', '0015_alter_anonchat_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonchat',
            name='joiners',
            field=models.ManyToManyField(blank=True, related_name='ch_messagengers', to='agl.annon'),
        ),
    ]
